export const doctors = [
  {
    id: 1,
    imgSrc: 'https://img.freepik.com/premium-photo/close-up-portrait-young-woman-doctor_274222-16353.jpg?w=996',
    name: 'Doctor Name 1',
    specialization: 'Orthopedic',
    experience: 10,
    rating: 4.5,
    consultationFee: 500,
    availability: 'Mon-Fri, 10 AM - 5 PM',
    contact: {
      phone: '+1234567890',
      email: 'doctor1@example.com',
    },
    location: 'New York, NY',
    services: ['Joint Replacement', 'Fracture Treatment', 'Sports Injuries'],
    description: 'Experienced orthopedic specialist with over 10 years of expertise in treating bone and joint disorders.',
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/doctor-white-coat-using-digital-tablet-reading-medical-data-gadget-working-hospital-standin_1258-87435.jpg?w=996',
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
    description: 'Renowned neurologist specializing in advanced treatments for brain and nervous system disorders.',
  },
  {
    id: 3,
    imgSrc: 'https://img.freepik.com/premium-photo/close-up-portrait-his-he-nice-attractive-content-experienced-cheerful-cheery-bearded-guy-ceo-boss-chief-director-med-expert-visit-folded-arms-isolated-light-white-gray-pastel-color_274222-20798.jpg?w=996',
    name: 'Doctor Name 3',
    specialization: 'Cardiologist',
    experience: 15,
    rating: 4.7,
    consultationFee: 1000,
    availability: 'Wed-Fri, 9 AM - 3 PM',
    contact: {
      phone: '+1234567892',
      email: 'doctor3@example.com',
    },
    location: 'San Francisco, CA',
    services: ['Heart Surgery', 'ECG Testing', 'Angioplasty'],
    description: 'Highly skilled cardiologist with 15 years of experience in heart surgery and cardiovascular treatments.',
  },
  {
    id: 4,
    imgSrc: 'https://img.freepik.com/free-photo/smiling-doctor-with-strethoscope-isolated-grey_651396-974.jpg?semt=ais_hybrid',
    name: 'Doctor Name 4',
    specialization: 'Dermatologist',
    experience: 5,
    rating: 4.2,
    consultationFee: 400,
    availability: 'Mon-Sat, 11 AM - 4 PM',
    contact: {
      phone: '+1234567893',
      email: 'doctor4@example.com',
    },
    location: 'Seattle, WA',
    services: ['Skin Treatment', 'Hair Loss Solutions', 'Allergy Testing'],
    description: 'Dedicated dermatologist offering advanced skin care treatments and solutions for hair and nail health.',
  },
  {
    id: 5,
    imgSrc: 'https://img.freepik.com/premium-photo/portrait-male-doctor-with-stethoscope-arm-cross-isolated-white-wall-health-insurance-concept_3544-1512.jpg?semt=ais_hybrid',
    name: 'Doctor Name 5',
    specialization: 'General Physician',
    experience: 12,
    rating: 4.6,
    consultationFee: 600,
    availability: 'Mon-Fri, 8 AM - 2 PM',
    contact: {
      phone: '+1234567894',
      email: 'doctor5@example.com',
    },
    location: 'Chicago, IL',
    services: ['General Checkup', 'Vaccinations', 'Health Consultation'],
    description: 'Experienced general physician providing comprehensive health consultations and routine care.',
  },
];

export const doctorSpecializations = [
  { id: 1, name: 'General Physician', description: 'General health and wellness checks.' },
  { id: 2, name: 'Cardiologist', description: 'Specializes in heart and cardiovascular health.' },
  { id: 3, name: 'Dermatologist', description: 'Focuses on skin, hair, and nail health.' },
  { id: 4, name: 'Orthopedic', description: 'Deals with bone and joint disorders.' },
  { id: 5, name: 'Neurologist', description: 'Specializes in brain and nervous system health.' },
];
