export const doctors = [
  {
    id: 1,
    imgSrc: 'https://img.freepik.com/premium-photo/close-up-portrait-young-woman-doctor_274222-16353.jpg?w=996 ', // replace with actual .jpg link
    name: 'Doctor Name 1',
    specialization: 'Orthopedic',
    experience: 10,
    rating: 4.5,
    consultationFee: 500,
    availability: 'Mon-Fri, 10 AM - 5 PM',
    contact: {
      phone: '+1234567890',
      email: 'doctor1@example.com',
    },
    location: 'New York, NY',
    services: ['Joint Replacement', 'Fracture Treatment', 'Sports Injuries'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/doctor-white-coat-using-digital-tablet-reading-medical-data-gadget-working-hospital-standin_1258-87435.jpg?t=st=1734273640~exp=1734277240~hmac=3bec44be500bdc95cc24f4bca379ab5bb14df4e8188d5243ef3380f9fe50b9b4&w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/close-up-portrait-his-he-nice-attractive-content-experienced-cheerful-cheery-bearded-guy-ceo-boss-chief-director-med-expert-visit-folded-arms-isolated-light-white-gray-pastel-color_274222-20798.jpg?w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/smiling-doctor-with-strethoscope-isolated-grey_651396-974.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/portrait-male-doctor-with-stethoscope-arm-cross-isolated-white-wall-health-insurance-concept_3544-1512.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/young-handsome-physician-medical-robe-with-stethoscope_1303-17820.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/young-male-doctor-white-suit-with-blue-stethoscope-holding-notepad-smiling_140725-29525.jpg?t=st=1734273755~exp=1734277355~hmac=b22dfaa00f255a49ca7671db85404e6889df8d537af148113b63d57d5789ece3&w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/young-man-doctor-wearing-white-coat-stethoscope-looking-confident-with-crossed-arms-1_141793-12597.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/pretty-young-smiling-clinician-whitecoat-crossing-arms-chest-while-looking-you-isolation_274679-4878.jpg?w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/young-man-doctor-wearing-white-coat-stethoscope-looking-confident-with-crossed-arms-1_141793-12597.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/doctors-day-cute-young-handsome-man-lab-coat-glasses-writing-notebook_140725-162888.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/pretty-young-smiling-clinician-whitecoat-crossing-arms-chest-while-looking-you-isolation_274679-4878.jpg?w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/close-up-portrait-his-he-nice-attractive-content-experienced-cheerful-cheery-bearded-guy-ceo-boss-chief-director-med-expert-visit-folded-arms-isolated-light-white-gray-pastel-color_274222-20798.jpg?w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/close-up-portrait-his-he-nice-attractive-content-experienced-cheerful-cheery-bearded-guy-ceo-boss-chief-director-med-expert-visit-folded-arms-isolated-light-white-gray-pastel-color_274222-20798.jpg?w=996', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/young-man-doctor-wearing-white-coat-stethoscope-looking-confident-with-crossed-arms_141793-12596.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/free-photo/young-woman-doctor-white-coat-with-stethoscope-smiling-confident-standing-with-arms-crossed-white-wall_141793-47701.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  {
    id: 2,
    imgSrc: 'https://img.freepik.com/premium-photo/portrait-male-doctor-with-stethoscope-arm-cross-isolated-white-wall-health-insurance-concept_3544-1512.jpg?semt=ais_hybrid', 
    name: 'Doctor Name 2',
    specialization: 'Neurologist',
    experience: 8,
    rating: 4.8,
    consultationFee: 700,
    availability: 'Tue-Thu, 12 PM - 6 PM',
    contact: {
      phone: '+1234567891',
      email: 'doctor2@example.com',
    },
    location: 'Los Angeles, CA',
    services: ['Migraine Management', 'Stroke Rehabilitation', 'Nerve Disorders'],
  },
  
];

  


  export const doctorSpecializations = [
    { id: 1, name: "General Physician", description: "General health and wellness checks." },
    { id: 2, name: "Cardiologist", description: "Specializes in heart and cardiovascular health." },
    { id: 3, name: "Dermatologist", description: "Focuses on skin, hair, and nail health." },
    { id: 4, name: "Orthopedic", description: "Deals with bone and joint disorders." },
    { id: 5, name: "Neurologist", description: "Specializes in brain and nervous system health." },
  ];